public enum EstadoAcomodador {
    INICIAR_TRABAJO,
    ESPERAR_EN_LA_SALA,
    REVISAR_EL_BOLETO,
    LLEVAR_AL_CLIENTE_HACIA_EL_LUGAR,
    REGRESAR_A_SU_PUESTO,
    ESPERAR_ASIENTOS_DISPONIBLES,
    TURNO_ACABADO,
    
}