public enum EstadoCliente {
    ENTRAR_AL_CINE,
    COMPRAR_BOLETO,
    COMPRAR_DULCES,
    RECIBIR_COMIDA,
    RECOGER_BOLETOS,
    CAMINAR_A_LA_DULCERIA,
    CAMINAR_A_LA_SALA,
    CAMINAR_AL_BAÑO,
    ESPERAR_AL_ACOMODADOR,
    CAMINAR_AL_ASIENTO,
    SENTARSE,
    VER_LA_PELICULA,
    CAMINAR_A_LA_SALIDA,
}


